#!/bin/bash -e

# $root -- machine root directory
# ${argv[@]} -- CLI arguments

# you can override qemu command here
#qemu=('qemu-system-x86_64')

# set up mac address here if you want it to be static
#macaddr="DE:AD:BE:EF:00:00"

# set up bridge interface if you do not want to use default
#bridge="br0"

# qemu arguments
#arguments=(-nographic -m 2G -hda "$root/img.qcow" "${argv[@]}")
